### ISSUE TITLE
where to  execute docker-compose-init bash file its not clear in the readme file please help

### ISSUE THREAD

**Issue by rkm1973** [pondix/docker-mysql-proxysql#3]
where to  execute docker-compose-init bash file its not clear in the readme file please help

Thanks

**Comment by pondix** [comment]
From the directory where you have cloned the repository e.g.:

```
[root@server]# git clone https://github.com/pondix/docker-mysql-proxysql.git
Cloning into 'docker-mysql-proxysql'...
remote: Enumerating objects: 222, done.
remote: Total 222 (delta 0), reused 0 (delta 0), pack-reused 222
Receiving objects: 100% (222/222), 2.63 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (117/117), done.
[root@server]# cd docker-mysql-proxysql/
[root@server]# ./docker-compose-init.bash 
```

**Comment by rkm1973** [comment]
Thanks, having issues while executing the ./docker-compose-init.bash en as follows:
./docker-compose-init.bash
: No such file or directory line 2: constants
./docker-compose-init.bash: line 3: $'\r': command not found
##################################################################################
# Started ProxySQL / Orchestrator / MySQL Docker Cluster Provisioner!            #
##################################################################################
./docker-compose-init.bash: line 9: $'\r': command not found
sleep: invalid time interval ‘1\r’
Try 'sleep --help' for more information.
./docker-compose-init.bash: line 11: $'\r': command not found
./docker-compose-init.bash: line 12: docker-compose: command not found
: No such file or directoryh: line 2: constants
./bin/docker-mysql-post.bash: line 3: $'\r': command not found
./bin/docker-mysql-post.bash: line 56: syntax error: unexpected end of file
./docker-compose-init.bash: line 14: $'\r': command not found
./docker-compose-init.bash: line 18: syntax error: unexpected end of file

Please help
Thanks
