### ISSUE TITLE
: No such file or directory line 2: constants

### ISSUE THREAD

**Issue by rkm1973** [pondix/docker-mysql-proxysql#4]
having issues while executing the ./docker-compose-init.bash en as follows:
./docker-compose-init.bash
: No such file or directory line 2: constants
./docker-compose-init.bash: line 3: $'\r': command not found
##################################################################################

Started ProxySQL / Orchestrator / MySQL Docker Cluster Provisioner!
##################################################################################
./docker-compose-init.bash: line 9: $'\r': command not found
sleep: invalid time interval ‘1\r’
Try 'sleep --help' for more information.
./docker-compose-init.bash: line 11: $'\r': command not found
./docker-compose-init.bash: line 12: docker-compose: command not found
: No such file or directoryh: line 2: constants
./bin/docker-mysql-post.bash: line 3: $'\r': command not found
./bin/docker-mysql-post.bash: line 56: syntax error: unexpected end of file
./docker-compose-init.bash: line 14: $'\r': command not found
./docker-compose-init.bash: line 18: syntax error: unexpected end of file

Please help
Thanks

**Comment by pondix** [comment]
What operating system is this? Only linux / mac / unix is supported

**Comment by rkm1973** [comment]
Hi,

I have installed Windows subsystem for Linux (bash shell) on windows Laptop.
Actually I am trying to set the container on docker for windows, hope its a right and supported os too.

Thanks and Regards,
Rish
________________________________

**Comment by rkm1973** [comment]
so windows is out of question ?

**Comment by pondix** [comment]
I have built these scripts specifically for Linux, they happen to work on MacOS... I'm not sure how the Windows subsystem for Linux works, but you'll need to have all the other associated packages / tools compiled there as well (e.g. orchestrator / sysbench / jq / etc..) 

There is nothing stopping you from trying :) however I don't plan to extend the scripts to support Windows at this stage.

**Comment by rkm1973** [comment]
Thanks for the update and your time, much appreciated

Regards
